name: LCT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Git Submodule Update
      run: |
        cd lct-backend && git pull --allow-unrelated-histories
        git submodule update --remote --recursive --merge --force
